spring:
  application:
    name: redis-app-tutorial
  cache:
    type: redis
  redis:
    host: localhost
    port: 6380
  datasource:
    url: jdbc:mysql://localhost:3306/redis_tutorial?useSSL=false&severTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true